name: Deploy to GitHub Pages
on: [push]
jobs:
  run-test-cases:
    runs-on: ubuntu-latest
    steps:
      - name: checkout the code
        uses: actions/checkout@v2

      - name: build docker image
        run: docker build . -t kodega/react-test -f Dockerfile.dev

      - name: run test cases
        run: docker run kodega/react-test npm run test -- --coverage
  deploy:
    runs-on: ubuntu-latest
    needs: run-test-cases
    steps:
      - name: checkout the code
        uses: actions/checkout@v2

      - name: build docker image
        run: docker build . -t kodega2016/react-client

      - name: push docker image to docker hub
        uses: docker/build-push-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          repository: kodega2016/react-client
          tag_with_ref: true

      - name: deploy to github pages
        uses:
          peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./build
